language: csharp
solution: RaspberryModuleController.sln
install:
  - nuget restore RaspberryModuleController.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release RaspberryModuleController.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./src/ConfiguratorUnitTests/bin/Debug/netcoreapp3.1/ConfiguratorUnitTests.dll
  
  
