configuration: Release

# restire NuGet packages before running MSBuild
before_build:
  - nuget restore src/RaspberryModuleController.sln
  
# package application.
build:
  verbosity: minimal
  publish_wap: true
  
deploy_script:
- cmd: >-
    docker login --username Mirkmissen --password eK8gKYqe8kDpk41C+uVqrg==

    docker build -t ModuleController/Raspberry:latest .

    docker push ModuleController/Raspberry:latest