configuration: Release

# restire NuGet packages before running MSBuild
before_build:
  - nuget restore src/RaspberryModuleController.sln
  
# package application.
build:
  verbosity: minimal
  publish_wap: true
