configuration: Release

environment:
  dockerpass:
    secure: eK8gKYqe8kDpk41C+uVqrg==

# restire NuGet packages before running MSBuild
before_build:
  - nuget restore src/RaspberryModuleController.sln
  
# package application.
build:
  verbosity: minimal
  publish_wap: true
  
deploy_script:
- cmd: >-
    cd src    
    
    attrib /S -R
    
    docker login --username mirkmissen --password %dockerpass%
    
    docker build -t mirkmissen/modulecontroller:latest .
    
    docker push mirkmissen/modulecontroller:latest
